name: Triggers

on:
    push:

jobs:
    curl:
        runs-on: ubuntu-latest
        steps:
            - name: Run Command
            - run: |
                curl -XPOST -u "${{ secrets.PAT_USERNAME}}:${{secrets.PAT_TOKEN}}" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" https://api.github.com/repos/moiSentineL/moisentinel.github.io/actions/workflows/eleventy_build.yaml/dispatches --data '{"ref": "main"}'
